package leetcode.easy;

public class Q_389_FindTheDifference {

    /*
     *
     * You are given two strings s and t.
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * Return the letter that was added to t.
     * */

    public static void main(String[] args) {

    }

    public char findTheDifference(String s, String t) {

        char[] s1 = s.toCharArray();
        char[] t1 = t.toCharArray();

        int[] ans = new int[26];

        for (char c : s1) {

            ans[c - 'a']++;

        }

        for (char c : t1) {

            ans[c - 'a']--;

        }

        for (char c : t1) {
            if (ans[c - 'a'] < 0) {
                return c;
            }
        }

        return '0';
    }
}
